minor bugfixes

diff --git a/powscript b/powscript
--- a/powscript
+++ b/powscript
@@ -10,15 +10,20 @@ settings='# Generated by POWSCRIPT (https://github.com/coderofsalvation/powscrip
 # Unless you like pain: edit the .pow sourcefiles instead of this file
 
 # powscript general settings
-set -e                         # halt on error
-set +m                         #
-SHELL="$(echo $0)"             # shellname
-SHELLNAME="$(basename $SHELL)" # shellname without path
-shopt -s lastpipe              # flexible while loops (maintain scope)
-shopt -s extglob               # regular expressions
+set -e                                # halt on error
+set +m                                #
+SHELL="$(echo $0)"                    # shellname
+shopt -s lastpipe                     # flexible while loops (maintain scope)
+shopt -s extglob                      # regular expressions
 path="$(pwd)"
-selfpath="$( dirname "$(readlink -f "$0")" )"
-tmpfile="/tmp/$(basename $0).tmp.$(whoami)"'
+if [[ "$BASH_SOURCE" == "$0"  ]];then #
+  SHELLNAME="$(basename $SHELL)"      # shellname without path
+  selfpath="$( dirname "$(readlink -f "$0")" )"
+  tmpfile="/tmp/$(basename $0).tmp.$(whoami)"
+else
+  selfpath="$path"
+  tmpfile="/tmp/.dot.tmp.$(whoami)"
+fi'
 strictmode='shopt compat40 2>&1 | grep invalid &>/dev/null && { echo "this app runs on bash >= 4.x, please upgrade"; exit 1;  }
 { 
   # enable strict bash 4.0 mode by disabling higher modes
@@ -41,15 +46,20 @@ shopt(){
 # Unless you like pain: edit the .pow sourcefiles instead of this file
 
 # powscript general settings
-set -e                         # halt on error
-set +m                         #
-SHELL="$(echo $0)"             # shellname
-SHELLNAME="$(basename $SHELL)" # shellname without path
-shopt -s lastpipe              # flexible while loops (maintain scope)
-shopt -s extglob               # regular expressions
+set -e                                # halt on error
+set +m                                #
+SHELL="$(echo $0)"                    # shellname
+shopt -s lastpipe                     # flexible while loops (maintain scope)
+shopt -s extglob                      # regular expressions
 path="$(pwd)"
-selfpath="$( dirname "$(readlink -f "$0")" )"
-tmpfile="/tmp/$(basename $0).tmp.$(whoami)"
+if [[ "$BASH_SOURCE" == "$0"  ]];then #
+  SHELLNAME="$(basename $SHELL)"      # shellname without path
+  selfpath="$( dirname "$(readlink -f "$0")" )"
+  tmpfile="/tmp/$(basename $0).tmp.$(whoami)"
+else
+  selfpath="$path"
+  tmpfile="/tmp/.dot.tmp.$(whoami)"
+fi
 declare -A footer
 footer["async"]="
 # wait for all async child processes (because \"await ... then\" is used in powscript)
@@ -107,7 +117,7 @@ stack_pop(){
 stack_update(){
   indent_last="$indent_current"
   indent_current=$(getindent "$1")
-  [[ -n $DEBUG ]] && echo ">> $indent_last|$indent_current|stacksize:${#stack[@]}"
+  [[ -n $DEBUG ]] && echo "\# debug: $indent_current|$indent_last|${#stack[@]} (indentlevel|last indentlevel|stackposition) "
   if ((indent_current < indent_last)); then stack_pop "$1"; fi
 }
 
@@ -306,7 +316,8 @@ line_is_multistring(){
 }
 
 check_literal(){
-  if line_is_multistring "$1"; then 
+  local line="${1/ # */}"
+  if line_is_multistring "$line"; then 
     if (( literal == 0 )); then 
       literal=1
     else
@@ -518,7 +529,7 @@ json_decode(){
 
   varname="$1"
   code="$code$( sed 'N;s/\n//g' | json_tokenize | json_parse | awk '{print "'$varname'"$0}')"
-  code="$(echo -e "$code" | sed  's/.*\[\].*//g;s/\t/=/g;s/",/./g;s/[,.]"/./g;s/.*=[{\[].*//g;s/\"\]=/]=/g;s/\]=/"\]=/g' )"
+  code="$(echo -e "$code" | sed  's/.*\[\].*//g;s/\t/=/g;s/",/./g;s/[,.]"/./g;s/.*=[{\[].*//g;s/\"\]=/]=/g;s/\]=/"\]=/g' | grep -vE '(-.*".*:)' )"
   eval "$code"
 } 
 # example: foreach foo keys
@@ -603,7 +614,7 @@ empty "$1" && {
   echo 'Usage:
     
    powscript <file.pow>                                     run powscript directly                        
-   powscript --compile [--sh] <file.pow>                    compile to bash [or (experimental) POSIX sh]  
+   powscript --compile [--sh] [--sourceable] <file.pow>     compile to bash [or (experimental) POSIX sh] [sourceable output] 
    powscript --lint <file.pow>                              crude linter                                  
    powscript --evaluate <powscript string>                  run powscript string directly                 
    powscript --interactive                                  interactive console                            
@@ -615,7 +626,7 @@ empty "$1" && {
                                                                                                           
                                                                                                           
    note: PIPE=1 allows input from stdin, PIPE=2 as well   ┌─────────────────────────────────────────────────────┐
-   but without the fat                                    │ powscript version '$POW_VERSION'                               │
+   but without the fat (no header/footercode)             │ powscript version '$POW_VERSION'                               │
                                                           │ docs: https://github.com/coderofsalvation/powscript │
   ';
 }
@@ -624,6 +635,10 @@ for arg in "$@"; do
   case "$arg" in
     --sh)
       runtime=sh
+      shift
+      ;;
+    --sourceable)
+      noheaderfooter=1
       shift
       ;;
     --tosh)
@@ -661,7 +676,7 @@ transpile_sh(){
       | sed "s/\[\[/\[/g;s/\]\]/\]/g"               \
       | sed "s/ == / = /g"                          \
       | sed "s/\&>\(.*[^;]\)[; $]/1>\1 2>\1; /g"    \
-      | transpile_all
+      | transpile_all                               
   fi
 }
 
@@ -685,7 +700,7 @@ transpile_sugar(){
       [[ "$line" =~ ^([ ]*while )                        ]] && transpile_while "$line"                      && continue
       [[ "$line" =~ ^([ ]*case )                         ]] && transpile_case "$line"                       && continue
       [[ "$line" =~ ([a-zA-Z_0-9]\+=)                    ]] && transpile_array_push "$line"                 && continue
-      [[ "$line" =~ ^([a-zA-Z_0-9:]*\([a-zA-Z_0-9, ]*\)) ]] && transpile_function "$line"                   && continue
+      [[ "$line" =~ ^([a-zA-Z_0-9:\.]*\([a-zA-Z_0-9, ]*\)) ]] && transpile_function "$line"                   && continue
       echo "$line" | transpile_all
     else 
       echo "$line"
@@ -749,10 +764,11 @@ compile(){
     echo -e "$settings"
   }
   transpile_sugar "$tmpfile" | grep -v "^#" > $tmpfile.code
+  sed -i 's/\\#/#/g' $tmpfile.code
   transpile_functions $tmpfile.code
   {
     cat $tmpfile.code
-    [[ ! $PIPE == 2 ]] && for i in ${!footer[@]}; do echo "${footer[$i]}"; done 
+    [[ ! $PIPE == 2 && ! -n $noheaderfooter ]] && for i in ${!footer[@]}; do echo "${footer[$i]}"; done 
   } | transpile_sh
   rm $tmpfile
   rm $tmpfile.code
@@ -866,7 +882,7 @@ lint(){
 }
 
 lint_pipe(){
-  code="$(cat -)"
+  code="$(cat)"
   output="$(echo "$code" | awk -F"[  ]" '{ j=0; for(i=1;i<=NF && ($i=="");i++); j++; if( ((i-1)%2) != 0 ){ print "indent error: "$j" "$i; }  }')"
   if [[ ${#output} != 0 ]]; then 
     echo "$output" 1>&2
