work in progress [might break]

diff --git a/powscript b/powscript
--- a/powscript
+++ b/powscript
@@ -1,6 +1,8 @@
 #!/bin/bash
-set -e
-shopt -s extglob
+set -e                 # halt on error
+set +m                 #
+shopt -s lastpipe      # flexible while loops (maintain scope)
+shopt -s extglob       # regular expressions
 
 
 indent_current=0
@@ -43,9 +45,10 @@ stack_update(){
 transpile_all(){
   cat - | while IFS="" read line; do
     i=$(getindent "$line")
-    [[ "$line" =~ "={}" ]] && echo "$(makeindent $i)declare -A ${line/=\{\}/}" && continue
-    [[ "$line" =~ "=[]" ]] && echo "$(makeindent $i)declare -a ${line/=\[\]/}" && continue
-    [[ "$line" =~ \$[A-Za-z_0-9] ]] && line="$(echo "$line" | sed -E 's/([ =])\$([a-zA-Z_0-9]+)/\1"$\2"/gi' )"
+    [[ "$line" =~ ^(#) ]] && local _comment="#"
+    [[ "$line" =~ "={}" ]] && echo "$_comment$(makeindent $i)declare -A ${line/=\{\}/}" && continue
+    [[ "$line" =~ "=[]" ]] && echo "$_comment$(makeindent $i)declare -a ${line/=\[\]/}" && continue
+    [[ "$line" =~ \$[A-Za-z_0-9@] ]] && line="$(echo "$line" | sed -E 's/([ =])\$([a-zA-Z_0-9@]+)/\1"$\2"/gi' )"
     echo "$line"
   done
 }
@@ -75,11 +78,19 @@ transpile_for(){
 transpile_if(){
   push stack "fi"
   code="${1/if not/if \!}"
+  firstvar="${code/\! /}"
+  firstvar="$(echo "$firstvar" | awk '{ print $2 }')"
   code="${code//and /&& }"
   code="${code//or /|| }"
-  code="${code/if /if [[ }"
+  code="${code//> /-gt }"
+  code="${code//>= /-ge }"
+  code="${code//< /-lt }"
+  code="${code//<= /-le }"
+  code="${code//!= /-ne }"
+  [[ "$code" =~ (if[ ]) && "$firstvar" =~ ^([\"\$]) ]] && code="${code/if /if [[ }"
   code="${code/match /=~ }"
-  code="$code \]\]; then"
+  [[ "$code" =~ "[[" ]] && code="$code \]\]"
+  code="$code; then"
   code="${code// is / == }"
   echo "$code" | transpile_all
 }
@@ -109,7 +120,7 @@ transpile_function(){
   echo "$1{"
 }
 ######################### begin-of-powscript-functions
-powfunctions="compose empty foreach keys last map math on pick values"
+powfunctions="compose empty filter isset keys last map math on pick pipemap values"
 # compose function out of 2 functions
 # example: 
 #   compose functionname func2 func1
@@ -122,35 +133,33 @@ compose() {
 empty(){
   [[ "${#1}" == 0 ]] && return 0 || return 1
 }
-# foreach
-# example:
-#   source ./foreach
-#   declare -A foo[0]="one" foo[1]="two" foo["bar"]="BAR"
-#                                                                                                                        
-#   bar(){ echo "$1 -> $2"; }
-#   foreach foo bar
-#   foreach foo keys | grep [0-1] | map pick foo
-foreach(){ 
-  eval "for i in \"\${!$1[@]}\"; do $2 \"\$i\" \"\$( echo \"\${$1[\$i]}\" )\"; done"
+# usage: filter foo myfunc
+filter(){
+  map $1 | pipemap $2 
+}
+# example: isset "" && echo "not empty string" || echo "empty string"
+isset(){
+  [[ ! "${#1}" == 0 ]] && return 0 || return 1
 }
 # example: foreach foo keys
 keys(){
   echo "$1"
 }
 last(){
-  [[ ! -n $2 ]] && return 1 || eval "echo \${$1[$2]:(-1)}"
+  [[ ! -n $1 ]] && return 1 
+  echo eval "echo \${$1[@]:(-1)}"
 }
 # maps a pipe stream to individual calls
 # example:
-#  foreach foo values | map echo
+#  map foo somefunction
 map(){
-  set +m ; shopt -s lastpipe
-  cat - | while read line; do "$@" "$line"; done
+  local arr="$1"; shift; local func="$1"; shift;
+  eval "for i in \"\${!$arr[@]}\"; do $func \"\$@\" \"\$i\" \"\${$arr[\$i]}\"; done"
 }
 math(){
   if [[ -n "$2" ]]; then
     which bc &>/dev/null && { echo "scale=$2;$1" | bc; } || echo "bc is not installed"; 
-  else echo $(("$1")); fi
+  else echo $(($1)); fi
 }
 #  1) SIGHUP	 2) SIGINT	 3) SIGQUIT	 4) SIGILL	 5) SIGTRAP
 #  6) SIGABRT	 7) SIGBUS	 8) SIGFPE	 9) SIGKILL	10) SIGUSR1
@@ -176,7 +185,13 @@ on() {
 #trap_with_arg func_trap INT TERM EXIT
 # example: pick foo "index"
 pick(){                                                                         
-  [[ ! -n $2 ]] && return 1 || eval "echo \${$1[$2]}"
+  [[ ! -n $2 ]] && return 1 
+  local output="$(eval "echo \${$1[$2]}")"
+  [[ ! ${#output} == 0 ]] && echo "$output" 
+}
+pipemap(){
+  func="$1"; shift
+  cat - | while read line; do $func "$@" "$line"; done
 }
 # example: foreach foo values
 values(){
@@ -241,15 +256,15 @@ cat_requires(){
 transpile_functions(){
   # *FIXME* this is bruteforce: if functionname is mentioned in textfile, include it
   while IFS="" read line; do 
-    regex="(${powfunctions// /|})"                                                  # include powscript-functions
+    regex="((^|[ ])${powfunctions// /[ ]|(^|[ ])})"                                                  # include powscript-functions
     echo "$line" | grep -qE "$regex" && {
       for func in $powfunctions; do
-        [[ "$line" =~ ^([ ]*)$func([ ]*) ]] && includefuncs="$includefuncs $func"
+        [[ "$line" =~ ([ ]?$func[ ]?) ]] && includefuncs="$includefuncs $func"
       done;
     }
   done <  $1
   [[ ! ${#includefuncs} == 0 ]] && echo -e "#\n# generated by powscript (https://github.com/coderofsalvation/powscript)\n#\n"
-  for func in $includefuncs; do declare -f $func; done
+  for func in $includefuncs; do declare -f $func; echo ""; done
 }
 
 compile(){
