minor bugfixes

diff --git a/powscript b/powscript
--- a/powscript
+++ b/powscript
@@ -428,27 +428,23 @@ transpile_sugar(){
     [[ "$line" =~ ([a-zA-Z_0-9]\+=)                   ]] && transpile_array_push "$line"                 && continue
     [[ "$line" =~ ^([a-zA-Z_0-9:]*\([a-zA-Z_0-9, ]*\)) ]] && transpile_function "$line"                   && continue
     echo "$line" | transpile_all
-  done <  $1
+  done <  "$1"
   stack_update ""
 }
 
 cat_requires(){
   while IFS="" read -r line; do 
-    [[ "$line" =~ ^(require_cmd ) ]] && {                                           # include require_cmd dependency checks
+    if [[ "$line" =~ ^(require_cmd ) ]]; then                                           # include require_cmd dependency checks
       local cmd="${line//*require_cmd /}"; cmd="${cmd//[\"\']/}"
-      printf "%-30s %s\n" "which $cmd &>/dev/null" "|| { echo \"dependency error: it seems '$cmd' is not installed (please install it)\"; exit 1; }"
-    };
-    [[ "$line" =~ ^(require ) ]] && {                                               # include require-calls
+      printf "%-30s %s\n" "which $cmd &>/dev/null" "|| { echo \"dependency error: it seems '$cmd' is not installed (please install it)\"; }"
+    fi
+    if [[ "$line" =~ ^(require ) ]]; then                                               # include require-calls
       local file="${line//*require /}"; file="${file//[\"\']/}"
-      if [[ ! -f "$file" ]]; then
-        echo "could not require: $line" 1>&2; exit 1;
-        break;
-      else
-        echo -e "#\n# $line (included by powscript\n#\n"
-        cat "$file";
-      fi
-    };
-  done <  $1
+      if [[ ! -f $file ]]; then echo "echo 'compile error: couldn't find required file: $file'; exit 1;"; exit 1; fi
+      echo -e "#\n# $line (included by powscript\n#\n"
+      cat "$file";
+    fi
+  done < "$1"
 }
 
 transpile_functions(){
@@ -471,7 +467,7 @@ transpile_functions(){
          seen[$func]=true
        fi
     done;
-  done < $1
+  done < "$1"
   [[ ! ${#includefuncs} == 0 ]] && echo -e "#\n# generated by powscript (https://github.com/coderofsalvation/powscript)\n#\n"
   for func in $includefuncs; do 
     declare -f $func; echo ""; 
@@ -480,10 +476,9 @@ transpile_functions(){
 
 compile(){
   if [[ -n $PIPE ]]; then 
-    cat - | lint_pipe > $tmpfile
+    cat | lint_pipe > $tmpfile
   else
     local dir="$(dirname "$1")"; local file="$(basename "$1")"; cd "$dir" &>/dev/null
-    [[ ! -f "$file" ]] && { echo "no such file: $file"; exit 1; }
     { cat_requires "$file" ; echo -e "#\n# application code\n#\n"; cat "$file"; } | lint_pipe > $tmpfile
   fi
   [[ ! $PIPE == 2 ]] && {
@@ -512,7 +507,7 @@ process(){
 }
 
 evaluate(){
-  [[ -n $PIPE ]] && cat - > $tmpfile || echo -e "$*" | lint_pipe > $tmpfile
+  [[ -n $PIPE ]] && cat > $tmpfile || echo -e "$*" | lint_pipe > $tmpfile
   evalstr_cache="$evalstr_cache\n$*"
   [[ -n $DEBUG ]] && echo "$(transpile_sugar $tmpfile)"
   eval "$(transpile_sugar $tmpfile)"
